### ISSUE TITLE
AMDGPU RADV Vulkan performance issues [Arctic Islands Cards and possibly others too]

### ISSUE THREAD

**Issue by Lucy-Nya** [daniel-schuermann/mesa#130]
**Describe the bug**
Games using vulkan (via Radv) have a bad to Ok-isch performance and some even start to lag like crazy (No Mans Sky for example when u open a menu). This seems to be true for cards of the Arctic Islands Series (Issue found on a Polaris 10 Card)

The issue can be 'fixed' by copying the  "libvulkan_radeon.so" library from a binary mesa build and forcing a vulkan game to use it instead of the system one.
The frames are capped at 30 in my test but performance dips are the same with higher caps.

**Screenshots**
Performance before using arch's binary libvulkan_radeon.so:
https://i.imgur.com/zQvsoJ6.png

Performance while using them:
https://i.imgur.com/EJbdtre.png

And the Performance on Arch with it's binary Mesa:
https://i.imgur.com/7u6PjDV.png

**System information:**
 - GPU: Radeon RX 570
 - ACO version: Mesa 19.3.0-devel (git-f2bed9b344) (Gentoo)

**Additional context**
Reproducing the Problem:
>*Starting No Mans Sky (Bug found on Arch) (Performance drop is very noticeable in NMS) with Arch Linux's Mesa + Vulkan Loader
>*Loading a save and open the inventory in-game (TAB)
Result: Performance is good and Menus work as they should

>*Installing Mesa-ACO
>*Starting the game with it, loading a save and the inventory again (TAB)
Result: Games run ok, but Menus run with ~13 fps and stutter alot

>*Again with Mesa-ACO but with the arch linux's mesa binary libvulkan_radeon.so library
Result: Games runs very well and smooth even in menus

**Comment by pendingchaos** [comment]
The NMS menu issue is a known issue (https://github.com/daniel-schuermann/mesa/issues/128) with a fix being worked on. Not sure if the issue also exists in-game or if the in-game performance issue you're having is a different issue.

How does NMS run without any menus open and with `RADV_PERFTEST=llvm`? This will have LLVM be used instead of ACO. If in-game performance is an upstream issue like with the menu, it should still happen with LLVM used.

Are there any other games with performance issues?

For Vulkan games, Mesa-ACO with arch linux's libvulkan_radeon.so is the the same as just Arch Linux's Mesa, by the way.

**Comment by Lucy-Nya** [comment]
Thanks for clarifying
and yes it runs the same with `RADV_PERFTEST=llvm` and the issue still appears. with the same performances as i posted.
i just find it really weird that loading the Arch's libvulkan_radeon.so on my gentoo system actually helps.
the issue occurs in arch aswell but only with mesa-aco-git. it happend on arch only when mesa is build from source. that's i've oberserverd atleast (on my system)
(mesa get's removed and replaced with mesa-aco-git in arch)

**Comment by Lucy-Nya** [comment]
sorry for the late reply on your question.

it was pretty much every game where vulkan is used for me (including games using D9VK/DXVK)
this only happens tho when building mesa-aco (and vanilla mesa) from source and is not be found of when using binaries. (i also included every flag as possible on my gentoo system to see if it is just me forgetting to set an important flag but it still kept lagging. and like i said replacing my 'libvulkan_radeon.so' with one that comes out of a binary 'fixes' the issue for me)

**Comment by ryao** [comment]
@pendingchaos We tried to investigate this from Gentoo, but we are not well versed in this infrastructure and not all of us have appropriate hardware for studying this, so we made very little progress. I just heard about this issue report. Here is some additional information that we know from further conversations with Lucy-San:

* Building regular Mesa on Arch using what should be the same PKGBUILD that the Arch developers did introduces the same regression. It suggests to us that the sources published by Arch do not match the sources used to build their binary, but none of us have looked into that in depth.
* Building Mesa on Gentoo against LLVM 10 HEAD resolves the issue. We were told that performance is better than Arch’s binary across the board when doing this, but we were not given numbers.

**Comment by ryao** [comment]
@pendingchaos Further testing by @PenguVoid found that building mesa master against LLVM 10 master resolves the NMS problem. We (at Gentoo) had been rather confused as to what the cause was of this due to a mix of miscommunication on version information, lack of familiarity with this code and a lack of developers who both had appropriate hardware and were willing to look into it. The tip about 74470baebbdacc8fd31c9912eb8c00c0cd102903 in #128 cleared up our confusion. Thanks for posting it.

**Comment by Venemo** [comment]
@PenguVoid Can you confirm that the issue is now gone?

**Comment by Lucy-Nya** [comment]
Oh yeah sorry. kinda forgot about that.
yep the issue resolved itself after some time and is completely gone for me
