### ISSUE TITLE
ACO graphics issues with RAGE2

### ISSUE THREAD

**Issue by jarrard** [daniel-schuermann/mesa#187]
LLVM has no image corruption (visible from main menu), ACO does.

AMD hardware, 6800XT. Mesa20 and 21 tested. 

Other games so far that have image corruption are GTA5 with ACO. 

Be nice if one day ACO was problem free.

**Comment by pendingchaos** [comment]
Please be more descriptive about the issue and use the bug tracker at https://gitlab.freedesktop.org/mesa/mesa/-/issues for future issues (this one isn't really used anymore). I think these two issues might be duplicates of existing issues anyways

The Rage 2 issue sounds like a duplicate of https://gitlab.freedesktop.org/mesa/mesa/-/issues/4163 ? This is fixed in Mesa 21.0-rc5 and newer and should also be fixed in the next 20.3

Is the GTA5 issue https://gitlab.freedesktop.org/mesa/mesa/-/issues/4192 ? For now, you can workaround this by using `RADV_DEBUG=llvm`, `RADV_DEBUG=invariantgeom` (Mesa 21.0 and newer) or `d3d11.invariantPosition=True` (enabled by default in DXVK 1.8 and newer)

**Comment by jarrard** [comment]
Yes is duplicate of that one issue it seems. I posted screenshots over in protons rage2 thread also.  
Yeah sorry I forgot all was going via freedesktop org. Thought something was off.

https://github.com/ValveSoftware/Proton/issues/2686

PS. Yeah I know about the work around to avoiding this issue by switching back to LLVM. Its just ACO is the default...
