### ISSUE TITLE
X4 Foundations: ACO exhibits lower performance than LLVM

### ISSUE THREAD

**Issue by edmondo** [daniel-schuermann/mesa#58]
I've created two renderdoc captures from X4, where LLVM renders faster than ACO (0ba58be607f5b).

LLVM: 52 FPS (817 MB)
https://drive.google.com/file/d/1NVTu0LA_LKmAajzwaRssiXCLb0bFjAdZ/view?usp=sharing

ACO: 46 FPS (823 MB)
https://drive.google.com/file/d/1NeFFu7Px8LFYTIDkgZLXbVd15VENkE1M/view?usp=sharing

Kernel: 5.1.0-gentoo
CPU: AMD Ryzen 5 2600
GPU: AMD RX 470 (AMD RADV/ACO POLARIS10 (LLVM 9.0.0))

**Comment by edmondo** [comment]
Retested with the new master (7157929d) and the performance regression persists.

I've tried to do some analysis with RenderDoc. Timings in colour passes #6 and #7 seem to be consistently higher.
Following screenshot shows differences of the fragment shader with the live driver disassembly, like bigger code size. I'm not sure if it's expected that the ACO disassembly shows only stats but no code.
![X4_2019-07-13-114739_1920x1080_scrot](https://user-images.githubusercontent.com/1729650/61170228-353dca80-a566-11e9-9be9-a8ca70c98e30.png)

**Comment by daniel-schuermann** [comment]
> Timings in colour passes #6 and #7 seem to be consistently higher.

Passes #3 and #4 are far more worrying if the timings are more or less accurate.
> Following screenshot shows differences of the fragment shader with the live driver disassembly, like bigger code size.

Are you sure that's the same shader? ACO has 8 Waves vs LLVM's 2, so despite the larger code size, I'd expect ACO to perform much better here.
> I'm not sure if it's expected that the ACO disassembly shows only stats but no code.

The problem is that we don't have our own disassembler, thus we use LLVM's to print asm (you can do that with RADV_DEBUG=shaders but that is probably too much if called on a complete capture). The overhead to call to LLVM for disassembly is unfortunately way too high to justify just for the comfort of always having the code right away.

**Comment by doitsujin** [comment]
> Passes #3 and #4 are far more worrying if the timings are more or less accurate.

The absolute numbers aren't accurate. Renderdoc heavily over-estimates execution time for render passes with many draw calls because it doesn't actually measure the time for the whole pass, but computes the sum of execution times of all the draw calls (which iirc is measured from `TOP_OF_PIPE` to `BOTTOM_OF_PIPE`, so it includes a lot of stuff things you don't really want to measure).

That said, pass 3 probably deserves to be looked at.

**Comment by edmondo** [comment]
> Passes #3 and #4 are far more worrying if the timings are more or less accurate.

I wouldn't trust too much the timing for pass #3 since it's jumping from 12k to 36k and pass #3 doesn't have a fragment shader.

> Are you sure that's the same shader? ACO has 8 Waves vs LLVM's 2, so despite the larger code size, I'd expect ACO to perform much better here.

Yes, I think that's the same shader. I compared the SPIR-V code and it's 100% equal.

**Comment by pendingchaos** [comment]
`echo "profile_standard" > /sys/class/drm/card0/device/power_dpm_force_performance_level` under root should make the timings much more consistent (and `echo "auto" > /sys/class/...` for when you're done). With this, passes #3 and #4 perform similarly for me.

Passes #6 and #7 can be improved by increasing `threshold` in `select_instruction`. I think it can also be improved by folding literals during re-materialization, though I haven't tested that.

Another way to improve performance is to improve NIR's loop unrolling pass to unroll the loops in passes #6 and #7. IIRC this gives the best performance.

**Comment by shmerl** [comment]
Just tested X4 using stock amdgpu settings and latest ACO build with llvm9:

**llvm:**
![x4_llvm](https://user-images.githubusercontent.com/310927/61179291-aebcd380-a5cd-11e9-8eff-58f9e52232ec.jpg)

**aco:**
![x4_aco](https://user-images.githubusercontent.com/310927/61179293-b8463b80-a5cd-11e9-8bcb-64b940621f4a.jpg)

So like above, llvm performs better.

**Comment by shmerl** [comment]
Setting ` /sys/class/drm/card0/device/power_dpm_force_performance_level` to `profile_standard` decreased performance for both, but llvm is still ahead in that case:

**llvm:**
![x4_llvm_profile_standard](https://user-images.githubusercontent.com/310927/61179367-fabc4800-a5ce-11e9-8635-ffbfbb678c36.jpg)

**aco:**
![x4_aco_profile_standard](https://user-images.githubusercontent.com/310927/61179368-00b22900-a5cf-11e9-8aeb-ea8cb42baf34.jpg)

**Comment by edmondo** [comment]
A lot of good work has been done in mesa and in ACO and the new performance values are looking better for LLVM and much better for ACO.

Tested with ACO master (42225d73)

**LLVM**: 58 - 59 FPS  _(before 52 FPS)_

**ACO**: 59 - 60 FPS  _(before 46 FPS)_

CPU: AMD Ryzen 5 2600
GPU: AMD RX 470
